### ISSUE TITLE
Can't download private channel/group's media

### ISSUE THREAD

**Issue by C3FF995BAE4** [bipinkrish/Save-Restricted-Bot#10]
Whenever I try to download from private channel/group, I got the below error
**Error** : _Telegram says: [400 MESSAGE_EMPTY]_
_The message sent is empty or contains invalid characters (caused by "messages.SendMessages")_

**Comment by bipinkrish** [comment]
What type of was the message?

**Comment by C3FF995BAE4** [comment]
Stickers, images, videos. Only scraping the plain text is working properly for private channel/group now.
This problem has been discovered since yesterday.

**Comment by Dr0gon23** [comment]
I have the same error when I use unnamed private channel links (example: t*me/c/11****/3****** ). instead if use a link that has a name in the channel (example t*me/namechannel/***** ) it works. 
can you fix?

**Comment by bipinkrish** [comment]
are you sure the account has access to that chat

**Comment by C3FF995BAE4** [comment]
Yes of course.

**Comment by bipinkrish** [comment]
I tested it, it is working fine. please use latest version.
