### ISSUE TITLE
Private group join error

### ISSUE THREAD

**Issue by C3FF995BAE4** [bipinkrish/Save-Restricted-Bot#13]
Thank you for fix, but I found new bug with latest code

When I send private group for join, bot return the error below:
Error : Telegram says: [400 BOT_METHOD_INVALID] - The method can't be used by bots (caused by "messages.ImportChatInvite")

So I manually entered the group and sent the link.
Then I got the following error: Error : Telegram says: [400 CHANNEL_INVALID] - The channel parameter is invalid (caused by "channels.GetChannels")

Is this just for me?

**Comment by bipinkrish** [comment]
You need to set string session of a account not bot

**Comment by C3FF995BAE4** [comment]
It looks like almost all the replit generators are dead. I will find another generator and try it :)
