### ISSUE TITLE
[Feature request] Add support to forward from bots which have restricted forwarding

### ISSUE THREAD

**Issue by Sra0ne** [bipinkrish/Save-Restricted-Bot#14]
Title

**Comment by bipinkrish** [comment]
It is not possible by design, telegram doesn't allow to copy message link in bot chats

**Comment by kkhanyaseen** [comment]
U can copy using thirt party apk like plus messenger.

**Comment by Morrigan-Ship** [comment]
> It is not possible by design, telegram doesn't allow to copy message link in bot chats

you can use newmessage event filter in telethon
send new message in bot if mssage contain 0-1:
then download all content from bot and save with reply in group chat id

**Comment by bipinkrish** [comment]
This is Done, see README

**Comment by Sra0ne** [comment]
> This is Done, see README

Great,thanks!
