### ISSUE TITLE
ImportError: cannot import  name 'url_quote' from 'werkzeug.urls'  (/app/.heroku/python/lib/python3.11/site -packages/werkzeug/urls.py)

### ISSUE THREAD

**Issue by tarunjangid12** [bipinkrish/Save-Restricted-Bot#19]
Please tell how to solve this error
![Screenshot_2023-10-02-10-22-50-31_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/bipinkrish/Save-Restricted-Bot/assets/146462019/05045ec6-901d-4a1f-9453-0bbc98c2233f)

**Comment by bipinkrish** [comment]
I updated flask version try again
