### ISSUE TITLE
Not an issue 

### ISSUE THREAD

**Issue by RevealedSoulEven** [bipinkrish/Save-Restricted-Bot#30]
Sorry for creating an issue. But I wanted to know the logic

Like I'm hosting it on my own computer but how does it uploads videos of 300+mb downloading them from the channel and reuploading in just few seconds?

And even I can't find the video downloaded to my local storage. So how does it do it??

What's the logic? Can you please explain. As I'm working on something very similar where I need this fast download speed to upload videos but I can't achieve this.

**Comment by bipinkrish** [comment]
It will download to local, upload and then delete, that's why you can't find it in local after upload. It uses standard media downloader and uploader functions from Pyrogram.

**Comment by RevealedSoulEven** [comment]
Oohhh then also the upload speed it just too high. I thought you've been using some threading or so to achieve it. But however, great project.
