### ISSUE TITLE
Am I doing something wrong? MessageEmpty

### ISSUE THREAD

**Issue by TruePhad** [bipinkrish/Save-Restricted-Bot#4]
I have done everything, I have configured my session, token, hash id, api id, etc. But when I send the post link to my bot I get the following in the console:

**pyrogram.errors.exceptions.bad_request_400.MessageEmpty: Telegram says: [400 MESSAGE_EMPTY] - The message sent is empty or contains invalid characters (caused by "messages.SendMessage")**

It should be noted that the link I am sending is from a private group, but the session is from my account that is in the group, so I don't know if I am doing something wrong, if you could suggest something it would be great.

**Comment by bipinkrish** [comment]
Can you give me more info

**Comment by TruePhad** [comment]
Sorry for the delay, I didn't get the notification on Github, I just checked my mail and you had already answered me, I'm really sorry.
Sure, what more information can I provide you?

**Comment by bipinkrish** [comment]
Like what message you tried this on or this happened before any interaction?
Is it private or public?
Full related logs if you can.

**Comment by TruePhad** [comment]
That is correct, the group is private and has this restriction of not being able to save messages. The type of link I have been sending is like this: https://t.me/c/1561578200/2243

The steps I did are as follows:
- I entered, the ID, Token of the bot, etc on 'app.json', like this:
"ID": {
          "description": "29381945",
          "required": true
        },
        "HASH": {
          "description": "2d53eabf3a8b3c8c7c2696dbccef0f29",
          "required": true
        },
        "TOKEN": {
          "description": "6229276940:AAFLn27DGPdPPHAaErL5a45YX6SxhyDusOI",
          "required": true
        },
- Then I open main.py and I still change my ID, my token, my session, etc.
- Then I started main.py
- Then I went to my bot and sent the link: https://t.me/c/1561578200/2243
- Nothing happens, but I go to the console where I started main.py and it appears:
pyrogram.errors.exceptions.bad_request_400.MessageEmpty: Telegram says: [400 MESSAGE_EMPTY] - The message sent is empty or contains invalid characters (caused by "messages.SendMessage").

Maybe in the modifications of those files I did it wrong?

**Comment by bipinkrish** [comment]
You don't have to give out your private IDs and Tokens, i suggest to revoke your token at botfather.

Are you sure https://t.me/c/1561578200/2243 this message exists? It is not deleted? Because I didn't handled deleted messages.

If you are using private chats means you have to set string session also.

**Comment by TruePhad** [comment]
Thank you very much, I will try and check everything, I will let you know if it worked.

**Comment by bipinkrish** [comment]
well...?
